"""Constants and enumeations used across the codebase."""

import typing

from enum import StrEnum


# types
JSONSerializable = typing.Union[str, int, float, bool, None, typing.Dict[str, typing.Any], typing.List]
JSON = typing.Dict[str, JSONSerializable]
JSONSchemaType = typing.Dict[str, str | typing.Dict[str, typing.Any] | typing.List[typing.Dict[str, typing.Any]]]

byte_types = (bytes, bytearray, memoryview)

# decorator constants
# naming
# state machine
ANY_STATE: str = "ANY_STATE"
UNSPECIFIED: str = "UNSPECIFIED"
# types


class ResourceTypes(StrEnum):
    """Exposed resource types."""

    PROPERTY = "PROPERTY"
    ACTION = "ACTION"
    EVENT = "EVENT"
    THING = "THING"


class REGEX(StrEnum):
    """Common regexes."""

    states = "[A-Za-z_]+[A-Za-z_ 0-9]*"
    url = r"[\-a-zA-Z0-9@:%._\/\+~#=]{1,256}"


class HTTP_METHODS(StrEnum):
    """Currently supported HTTP request methods."""

    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"
    PATCH = "PATCH"
    # OPTIONS = 'OPTIONS'


class ZMQ_TRANSPORTS(StrEnum):
    """
    Supported ZMQ transport protocols - TCP, IPC, INPROC.

    TCP - needs socket address additional specified like tcp://0.0.0.0:{port}
    IPC - within python, multiprocess applications, can be autogenerated
    INPROC - within python, multithreaded applications, can be autogenerated
    """

    TCP = "TCP"
    IPC = "IPC"
    INPROC = "INPROC"


class Operations(StrEnum):
    """WoT operations (both standard and non-standard)."""

    readproperty = "readproperty"
    writeproperty = "writeproperty"
    deleteproperty = "deleteproperty"
    observeproperty = "observeproperty"

    readmultipleproperties = "readmultipleproperties"
    writemultipleproperties = "writemultipleproperties"
    readallproperties = "readallproperties"
    writeallproperties = "writeallproperties"

    invokeaction = "invokeaction"
    subscribeevent = "subscribeevent"
    unsubscribevent = "unsubscribevent"


__all__ = [HTTP_METHODS.__name__, ZMQ_TRANSPORTS.__name__, Operations.__name__]
